In [3]:
import numpy as np
import pandas as pd

In [ ]:
# Thông tin về dữ liệu
info = pd.read_csv("../ml-100k/u.info", header=None, sep="\t")
info.head()

                0
0       943 users
1      1682 items
2  100000 ratings

In [ ]:
# Các loại occupation
occupation = pd.read_csv("../ml-100k/u.occupation", header=None, sep="\t")
print("Số lượng ngành nghề:")
print(len(occupation))
print("Các loại ngành nghề:")
print(occupation[0].tolist())

Các loại ngành nghề:
['administrator', 'artist', 'doctor', 'educator', 'engineer', 'entertainment', 'executive', 'healthcare', 'homemaker', 'lawyer', 'librarian', 'marketing', 'none', 'other', 'programmer', 'retired', 'salesman', 'scientist', 'student', 'technician', 'writer']
Số lượng ngành nghề:
21

In [21]:
# Các thể loại phim
genre = pd.read_csv("../ml-100k/u.genre", header=None, sep="\t")
print("Số lượng thể loại phim:")
print(len(genre))
print("Các thể loại phim:")
print(genre[0].tolist())

Số lượng thể loại phim:
19
Các thể loại phim:
['unknown|0', 'Action|1', 'Adventure|2', 'Animation|3', "Children's|4", 'Comedy|5', 'Crime|6', 'Documentary|7', 'Drama|8', 'Fantasy|9', 'Film-Noir|10', 'Horror|11', 'Musical|12', 'Mystery|13', 'Romance|14', 'Sci-Fi|15', 'Thriller|16', 'War|17', 'Western|18']

In [22]:
# Dữ liệu về người dùng
users = pd.read_csv("../ml-100k/u.user", header=None, sep="|")
users.columns = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [27]:
# Dữ liệu về phim
movies = pd.read_csv("../ml-100k/u.item", header=None, sep="|", encoding='latin-1')
movies.columns = ['movie_id', 'title', 'release_date', 'video_release_date', 'IMDb_URL'] + genre[0].tolist()
movies.head()

,movie_id,title,release_date,video_release_date,IMDb_URL,unknown|0,Action|1,Adventure|2,Animation|3,Children's|4,...,Fantasy|9,Film-Noir|10,Horror|11,Musical|12,Mystery|13,Romance|14,Sci-Fi|15,Thriller|16,War|17,Western|18
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
# Dữ liệu về Ratings
ratings = pd.read_csv("../ml-100k/u.data", header=None, sep="\t")
ratings.columns = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [29]:
# Gộp dữ liệu người dùng và ratings
user_ratings = pd.merge(ratings, users, on='user_id')
user_ratings.head()

   user_id  movie_id  rating  timestamp  age gender  occupation zip_code
0      196       242       3  881250949   49      M      writer    55105
1      186       302       3  891717742   39      F   executive    00000
2       22       377       1  878887116   25      M      writer    40206
3      244        51       2  880606923   28      M  technician    80525
4      166       346       1  886397596   47      M    educator    55113